title: The Skipped Breakpoint
author: Rahul Bothra

url: "https://pro-panda.github.io"
baseurl: ""

profile-picture: assets/profile.jpg
favicon_location: assets/favicon.ico

permalink: /title/
sass:
    style: compressed
    sass_dir: css

navbar:
 - name: "About"
   link: "about"
 - name: "Resume"
   link: "resume.pdf"
