title: Rahul Bothra
author: Rahul Bothra

url: "https://www.pro-panda.tech"
baseurl: ""

footer_url: "https://github.com/pro-panda/parchment"
footer_text: "This blog uses parchment theme"

profile-picture: assets/profile.jpg
favicon_location: assets/favicon.ico

permalink: /:year-:month-:day-:title/
sass:
    style: compressed
    sass_dir: css

navbar:
 - name: "About"
   link: "about"
 - name: "Resume"
   link: "resume.pdf"
