title: The Skipped Breakpoint
author: Rahul Bothra

url: "https://pro-panda.github.io"
baseurl: ""

favicon_location: assets/favicon.ico

permalink: /:year-:month-:day-:title/
sass:
    style: compressed
    sass_dir: css

navbar:
 - name: "About"
   link: "about"
 - name: "Resume"
   link: "resume.pdf"
 - name: "CV"
   link: "CV.pdf"
